package SMMID::Model::SMIDDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SMIDDB',
    
    
);

=head1 NAME

SMMID::Model::SMIDDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SMMID>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SMMIDDB::Result>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
